#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 25 21:06:22 2017

@author: Xin
"""

#3.3

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
age=[13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 25, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70]
len(age)

#smooth by bin average

for i in range(0, len(age), 3):
    print float((age[i]+age[i+1]+age[i+2]))/3

df = pd.DataFrame(age, columns=['age'])
df.plot()
df.plot.hist(bins=5)
plt.savefig('33hist.eps',format='eps', dpi=600)

df.plot()
df.plot.box()
plt.savefig('33box.eps', format='eps', dpi=600)

#3.7
#calculate age mean
np.mean(age)

#3.10
df.plot()
df.plot.hist(bins=10)
plt.savefig('37hist.eps',format='eps', dpi=600)

#3.11
age






